"""add language field to user

Revision ID: 81b53ab252e4
Revises: 3a67ce72339e
Create Date: 2026-01-07 08:36:43.907400

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# import pgvector

# revision identifiers, used by Alembic.
revision: str = "81b53ab252e4"
down_revision: Union[str, None] = "google_auth_001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removing drop_table commands to preserve password_reset_tokens
    op.add_column("users", sa.Column("language", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "language")
    # Removed recreation of password_reset_tokens since we didn't drop it
    # ### end Alembic commands ###
